services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "4200:80"
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
